#!/usr/bin/env bash

# Nice and simple. On subversion emacsdaemon checks for emacs version and links in the correct melpa dir.
# Here I intend to just use the stable release for now, but would still like the emd alias in bashrc to work.
alias emacsdaemon="emacs --daemon"

source /opt/homebrew/etc/bash_completion.d/git-prompt.sh
source /opt/homebrew/etc/bash_completion.d/mpc

# Change the blue to boldblue so it is legible. Note the leading E
# man ls for details
export LSCOLORS=Exfxcxdxbxegedabagacad
alias ls="ls -G"

# FIXME info nodes are not being set correctly, possibly because this path was being set
export INFOPATH="~/.info:/opt/homebrew/Cellar/emacs-head@29/29.2_1/share/info/emacs:"

# Completion stuff
# ================
# TODO this should probably be in acceptance_profile
# https://stackoverflow.com/a/58308956/1671119
export BASH_COMPLETION_COMPAT_DIR="/opt/homebrew/etc/bash_completion.d"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# This one makes __git_complete work for aliases like gp. Has to be manually loaded or it wont exist until after git commit is called.
[ -f /opt/homebrew/etc/bash_completion.d/git-completion.bash ] && . /opt/homebrew/etc/bash_completion.d/git-completion.bash
__git_complete gp _git_checkout

