#!/usr/bin/env bash
# This is where to add any acceptance specific PATH entries
# echo $PATH
# echo "Hello from .acceptance_profile"
PATH="/opt/homebrew/bin:$PATH"
export BASH_SILENCE_DEPRECATION_WARNING=1
