#!/usr/bin/env bash

# Now using hammerspoon to redirect this key.
# Remap § to ` for English keyboard
# hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000035,"HIDKeyboardModifierMappingDst":0x700000064}]}'

# fortune | cowsay | lolcat

source ~/Code/profile/kubernetes.sh
source ~/Code/profile/secrets.sh
source ~/Code/profile/java.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(zoxide init bash)"

alias aw="add-watermark"
alias ecp="export-customer-photos"
alias ce="EDITOR=vi crontab -e"

export MOUSE_MAC_ADDR="b8-f6-b1-22-b1-02"
export KEYBOARD_MAC_ADDR="7c-c3-a1-89-e0-ac"
alias cm="bluetoothconnector --connect $MOUSE_MAC_ADDR    --notify"
alias ck="bluetoothconnector --connect $KEYBOARD_MAC_ADDR --notify"
cb(){
    echo "connecting bluetooth devices"
    cm&
    ck&
}

function um(){
    diskutil unmount "/Volumes/$1";
}

alias ls="ls -G"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm use 13

eval "$(thefuck --alias)"

# Completion stuff
# ================
# https://stackoverflow.com/a/58308956/1671119
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# This one makes __git_complete work for aliases like gp. Has to be manually loaded or it wont exist until after git commit is called.
[ -f /usr/local/etc/bash_completion.d/git-completion.bash ] && . /usr/local/etc/bash_completion.d/git-completion.bash
__git_complete gp _git_checkout
