#!/usr/bin/env bash

# Now using hammerspoon to redirect this key.
# Remap § to ` for English keyboard
# hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000035,"HIDKeyboardModifierMappingDst":0x700000064}]}'

fortune | cowsay | lolcat

source ~/Code/profile/kubernetes.sh
source ~/Code/profile/secrets.sh
source ~/Code/profile/java.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(zoxide init bash)"

alias aw="add-watermark"
alias ecp="export-customer-photos"
alias ce="EDITOR=vi crontab -e"

export MOUSE_MAC_ADDR="b8-f6-b1-22-b1-02"
export KEYBOARD_MAC_ADDR="7c-c3-a1-89-e0-ac"
alias cm="bluetoothconnector --connect $MOUSE_MAC_ADDR    --notify"
alias ck="bluetoothconnector --connect $KEYBOARD_MAC_ADDR --notify"
cb(){
    echo "connecting bluetooth devices"
    cm&
    ck&
}

function um(){
    diskutil unmount "/Volumes/$1";
}

alias ls="ls -G"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(thefuck --alias)"
