#!/usr/bin/env bash
# echo "Hello from transcendence_profile" 
export PS1START="Transcendence"
export PS1COLOUR="\[\033[0;33m\]"
export GNOME22_USER_DIR="$HOME/.config/nemo"

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
source ".bashrc"
